// <auto-generated />
namespace attendance_beta2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class a10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a10));
        
        string IMigrationMetadata.Id
        {
            get { return "201904270254186_a10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
