// <auto-generated />
namespace attendance_beta2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _default : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_default));
        
        string IMigrationMetadata.Id
        {
            get { return "201904210947100_default"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
